# Generated by Django 5.1.7 on 2025-03-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_has_review_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='headline',
            new_name='title',
        ),
    ]
