# Generated by Django 5.1.7 on 2025-03-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_body_review_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='review_title',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='book_title',
        ),
    ]
