# Generated by Django 5.1.7 on 2025-04-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_title_review_review_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='book_title',
            new_name='title',
        ),
    ]
